name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with: 
          java-version: 1.8
      - name: Run with Gradle
        run: ./gradlew

      - name: Upload APK file
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: app
          # A file, directory or wildcard pattern that describes what to upload
          path: app/build/outputs/apk/debug/app-debug.apk
